<a href="https://colab.research.google.com/github/enzobanin/AnaliseDeDados/blob/main/sonoEstiloDeVida.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Sono e Estilo de Vida
##Dicionário


*    Person ID: Identificador do indivíduo
*    Gender: Gênero (Masculino/Feminino).
*   Age: Idade em anos.
*  Occupation: Profissão.
*   Sleep Duration (hours): Horas de sono por dia.
*   Quality of Sleep (scale: 1-10): Qualidade do sono (escala de 1 a 10)
*   Physical Activity Level (minutes/day): Atividade física diária (minutos).
*    Stress Level (scale: 1-10): Nível de estresse (escala de 1 a 10).
*  BMI Category: Categoria de IMC.
*   Blood Pressure (systolic/diastolic): Pressão arterial (sistólica/diastólica).
*   Heart Rate (bpm): Frequência cardíaca (bpm)
*   Daily Steps: Passos por dia.
*  Sleep Disorder: Distúrbio do sono (Nenhum, Insônia, Apneia do Sono).



##Descrição geral:
Base Fictícia composta por dados sobre hábitos de sono, saúde e estilo de vida de 400 indivíduos. Pode ser
usada para explorar a relação entre qualidade de vida e distúrbios do sono.

##Desafios de análise:
*   Investigar fatores que afetam a qualidade e duração do sono.
*   Relacionar estresse e atividade física com distúrbios.
*   Analisar indicadores de saúde cardiovascular

In [26]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [27]:
from google.colab import drive
drive.mount('/content/drive')

path = "/content/drive/MyDrive/Colab Notebooks/sonoEstiloDeVida"

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [28]:
df = pd.read_csv(path + '/02_sono_estilo_vida.csv', sep=',')
df.head()

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,NaN
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 374 entries, 0 to 373
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Person ID                374 non-null    int64
 1   Gender                   374 non-null    object
 2   Age                      374 non-null    int64
 3   Occupation               374 non-null    object
 4   Sleep Duration           374 non-null    float64
 5   Quality of Sleep         374 non-null    int64
 6   Physical Activity Level  374 non-null    int64
 7   Stress Level             374 non-null    int64
 8   BMI Category             374 non-null    object
 9   Blood Pressure           374 non-null    object
 10  Heart Rate               374 non-null    int64
 11  Daily Steps              374 non-null    int64
 12  Sleep Disorder           155 non-null    object
dtypes: float64(1), int64(7), object(5)
memory usage: 38.1+ KB

In [30]:
df.describe()

,Person ID,Age,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,Heart Rate,Daily Steps
count,374.000000,374.000000,374.000000,374.000000,374.000000,374.000000,374.000000,374.000000
mean,187.500000,42.184492,7.132086,7.312834,59.171123,5.385027,70.165775,6816.844920
std,108.108742,8.673133,0.795657,1.196956,20.830804,1.774526,4.135676,1617.915679
min,1.000000,27.000000,5.800000,4.000000,30.000000,3.000000,65.000000,3000.000000
25%,94.250000,35.250000,6.400000,6.000000,45.000000,4.000000,68.000000,5600.000000
50%,187.500000,43.000000,7.200000,7.000000,60.000000,5.000000,70.000000,7000.000000
75%,280.750000,50.000000,7.800000,8.000000,75.000000,7.000000,72.000000,8000.000000
max,374.000000,59.000000,8.500000,9.000000,90.000000,8.000000,86.000000,10000.000000

In [33]:
#Verificando se há valores nulos
((df.isnull().sum() / df.shape[0]) * 100).sort_values(ascending=False)

Sleep Disorder             58.55615
Gender                      0.00000
Age                         0.00000
Occupation                  0.00000
Person ID                   0.00000
Sleep Duration              0.00000
Quality of Sleep            0.00000
Stress Level                0.00000
Physical Activity Level     0.00000
BMI Category                0.00000
Blood Pressure              0.00000
Heart Rate                  0.00000
Daily Steps                 0.00000
dtype: float64